### ISSUE TITLE
Enhancement: Checking states

### ISSUE THREAD

**Issue by james-jlo-long** [Skateside/aria#2]
This will require a little research to ensure that this is how states work, but how about a way to interpret the state attribute value as a boolean?

```js
ARIA.asState = function (value) {

    return typeof value === "string"
        ? (/^(?:\s*true\s*)?$/i).test(value)
        : typeof value === "boolean"
            ? value
            : (value !== undefined && value !== null);

};
```

**Comment by Skateside** [comment]
Nice idea. Looked a few things up and it looks like that function won't cut it.
https://www.w3.org/WAI/PF/aria-1.1/states_and_properties#propcharacteristic_value

I'll integrate something like that, though. Cheers
